import {
    useState,
    useMemo,
    useRef,
    useEffect
} from "react";

import {
    BarChart,
    Bar,
    XAxis,
    YAxis,
    Tooltip,
    ResponsiveContainer,
    Cell,
    LabelList
} from "recharts";

import toast from "react-hot-toast";

import {
    Camera,
    X,
    MapPin
} from "lucide-react";

import {
    Badge
} from "../components/common/Badge";

import {
    PageHeader
} from "../components/common/PageHeader";

import {
    Modal
} from "../components/common/Modal";

import {
    api
} from "../services/api";


// ==============================
// FLEET OPS DISCLAIMER
// ==============================

const DataSourceNote = () => (

    <div

        style={{

            padding:
                "10px 14px",

            marginBottom:
                "20px",

            borderRadius:
                "6px",

            fontSize:
                "0.8rem",

            background:
                "rgba(14, 165, 233, 0.08)",

            border:
                "1px solid rgba(14, 165, 233, 0.25)",

            color:
                "var(--text-secondary)",

            display:
                "flex",

            alignItems:
                "center",

            gap:
                "8px"

        }}

    >

        <span

            style={{

                color:
                    "var(--info)",

                fontWeight:
                    700

            }}

        >

            ℹ Fleet Ops Module

        </span>


        Incidents listed here are illustrative
        fleet-logistics scenario data, not real
        events generated by the landslide ML model.
        Real landslide risk alerts are on the
        Alerts page.

    </div>

);


// ==============================
// ROOT-CAUSE COLORS
// ==============================

const CAUSE_COLORS = {

    "Landslide":
        "#ef4444",

    "Heavy Rainfall":
        "#f97316",

    "Bridge / Road Damage":
        "#f59e0b",

    "Mechanical Breakdown":
        "#3b82f6",

    "Overspeeding":
        "#6366f1"

};


const DEFAULT_COLOR =
    "#64748b";


// ==============================
// COMPONENT
// ==============================

export const Incidents = () => {


    // ==========================
    // STATE
    // ==========================

    const [
        isModalOpen,
        setIsModalOpen
    ] =
        useState(false);


    const [
        photoPreview,
        setPhotoPreview
    ] =
        useState(null);


    const [
        deaths,
        setDeaths
    ] =
        useState("");


    const [
        injuries,
        setInjuries
    ] =
        useState("");


    const [
        incidents,
        setIncidents
    ] =
        useState([]);


    const [
        incidentType,
        setIncidentType
    ] =
        useState(
            "Landslide"
        );


    const [
        locationText,
        setLocationText
    ] =
        useState("");


    const [
        submitting,
        setSubmitting
    ] =
        useState(false);


    const [
        coords,
        setCoords
    ] =
        useState(null);


    const [
        loading,
        setLoading
    ] =
        useState(true);


    const fileRef =
        useRef(null);


    // ==============================
    // LOAD INCIDENTS
    // ==============================

    const loadIncidents =
        async () => {

            try {

                setLoading(
                    true
                );


                const data =
                    await api.getIncidents();


                setIncidents(
                    Array.isArray(
                        data
                    )
                        ? data
                        : []
                );

            } catch (error) {

                console.error(
                    "Failed to load incidents:",
                    error
                );


                toast.error(
                    error.message ||
                    "Could not load incidents."
                );

            } finally {

                setLoading(
                    false
                );

            }

        };


    // ==============================
    // INITIAL LOAD
    // ==============================

    useEffect(() => {

        loadIncidents();

    }, []);


    // ==============================
    // PHOTO
    // ==============================

    const handlePhoto =
        (
            e
        ) => {

            const file =
                e.target.files?.[0];


            if (file) {

                setPhotoPreview(
                    URL.createObjectURL(
                        file
                    )
                );

            }

        };


    // ==============================
    // GET USER LOCATION
    // ==============================

    const getCurrentLocation =
        () => {

            return new Promise(
                (
                    resolve,
                    reject
                ) => {

                    if (
                        !navigator.geolocation
                    ) {

                        reject(

                            new Error(
                                "Geolocation is not supported by this browser."
                            )

                        );

                        return;

                    }


                    navigator.geolocation.getCurrentPosition(

                        resolve,

                        reject,

                        {

                            enableHighAccuracy:
                                true,

                            timeout:
                                8000,

                            maximumAge:
                                0

                        }

                    );

                }
            );

        };


    // ==============================
    // CAUSE BREAKDOWN
    // ==============================

    const causeData =
        useMemo(

            () => {

                const counts =
                    {};


                incidents.forEach(
                    incident => {

                        const cause =
                            incident.cause ??
                            incident.type ??
                            "Other";


                        counts[cause] =
                            (
                                counts[cause] ??
                                0
                            ) + 1;

                    }
                );


                return Object.entries(
                    counts
                )

                .map(

                    ([
                        cause,
                        count
                    ]) => ({

                        cause,

                        count

                    })

                )

                .sort(

                    (
                        a,
                        b
                    ) =>
                        b.count -
                        a.count

                );

            },

            [
                incidents
            ]

        );


    // ==============================
    // TOTALS
    // ==============================

    const total =
        incidents.length;


    const landslideCount =
        causeData.find(

            item =>
                item.cause ===
                "Landslide"

        )?.count ?? 0;


    const landslidePercent =
        total > 0

            ? Math.round(
                (
                    landslideCount /
                    total
                ) * 100
            )

            : 0;


    // ==============================
    // SEVERITY SORTING
    // ==============================

    const severityOrder = {

        CRITICAL:
            0,

        HIGH:
            1,

        MEDIUM:
            2,

        LOW:
            3,

        WARNING:
            4,

        INFO:
            5

    };


    const sortedIncidents =
        [
            ...incidents
        ].sort(

            (
                a,
                b
            ) =>

                (
                    severityOrder[
                        String(
                            a.severity ||
                            ""
                        ).toUpperCase()
                    ] ??
                    99
                )

                -

                (
                    severityOrder[
                        String(
                            b.severity ||
                            ""
                        ).toUpperCase()
                    ] ??
                    99
                )

        );


    // ==============================
    // RESET FORM
    // ==============================

    const resetForm =
        () => {

            setPhotoPreview(
                null
            );

            setDeaths(
                ""
            );

            setInjuries(
                ""
            );

            setLocationText(
                ""
            );

            setCoords(
                null
            );

            setIncidentType(
                "Landslide"
            );

            if (
                fileRef.current
            ) {

                fileRef.current.value =
                    "";

            }

        };


    // ==============================
    // CLOSE MODAL
    // ==============================

    const closeModal =
        () => {

            if (
                submitting
            ) {

                return;

            }


            setIsModalOpen(
                false
            );

            resetForm();

        };


    // ==============================
    // SUBMIT INCIDENT
    // ==============================

    const handleSubmit =
        async () => {

            // --------------------------
            // LOCATION TEXT
            // --------------------------

            if (
                !locationText.trim()
            ) {

                toast.error(
                    "Please enter the incident location."
                );

                return;

            }


            setSubmitting(
                true
            );


            try {

                // ======================
                // COORDINATES
                // ======================

                let latitude =
                    coords?.lat;


                let longitude =
                    coords?.lon;


                // ----------------------
                // GET CURRENT GPS
                // ----------------------

                if (
                    latitude == null ||
                    longitude == null
                ) {

                    try {

                        const position =
                            await getCurrentLocation();


                        latitude =
                            position.coords.latitude;


                        longitude =
                            position.coords.longitude;


                        setCoords({

                            lat:
                                latitude,

                            lon:
                                longitude

                        });

                    } catch (
                        geoError
                    ) {

                        let message =
                            "Unable to get your current location.";


                        if (
                            geoError.code ===
                            1
                        ) {

                            message =
                                "Location permission was denied. Please allow location access for this site.";

                        }

                        else if (
                            geoError.code ===
                            2
                        ) {

                            message =
                                "Your location could not be determined.";

                        }

                        else if (
                            geoError.code ===
                            3
                        ) {

                            message =
                                "Location request timed out.";

                        }


                        throw new Error(
                            message
                        );

                    }

                }


                // ======================
                // TYPE MAPPING
                // ======================

                const typeMap = {

                    "Landslide":
                        "LANDSLIDE",

                    "Heavy Rainfall":
                        "FLOOD",

                    "Bridge / Road Damage":
                        "ROAD_DAMAGE",

                    "Mechanical Breakdown":
                        "OTHER",

                    "Overspeeding":
                        "OTHER",

                    "Other":
                        "OTHER"

                };


                const backendType =
                    typeMap[
                        incidentType
                    ] ||
                    "OTHER";


                // ======================
                // SEVERITY
                // ======================

                const severity =

                    incidentType ===
                    "Landslide"

                        ? "HIGH"

                        : "MEDIUM";


                // ======================
                // DESCRIPTION
                // ======================

                let description =
                    locationText.trim();


                if (
                    deaths ||
                    injuries
                ) {

                    description +=

                        ` | Deaths: ${
                            deaths ||
                            0
                        }, Injuries: ${
                            injuries ||
                            0
                        }`;

                }


                // ======================
                // CREATE INCIDENT
                // ======================

                await api.createIncident({

                    type:
                        backendType,

                    severity:
                        severity,

                    description:
                        description,

                    location: {

                        type:
                            "Point",

                        coordinates: [

                            longitude,

                            latitude

                        ]

                    },

                    verified:
                        false,

                    status:
                        "ACTIVE"

                });


                // ======================
                // IMPORTANT:
                // RELOAD FROM BACKEND
                // ======================

                await loadIncidents();


                // ======================
                // CLOSE + RESET
                // ======================

                setIsModalOpen(
                    false
                );


                resetForm();


                toast.success(
                    "Incident reported successfully. Awaiting verification."
                );

            } catch (
                error
            ) {

                console.error(
                    "Incident submission error:",
                    error
                );


                toast.error(

                    error.message ||
                    "Could not report incident."

                );

            } finally {

                setSubmitting(
                    false
                );

            }

        };


    // ==============================
    // MODAL FOOTER
    // ==============================

    const modalFooter = (

        <>

            <button

                type="button"

                className="btn btn-secondary"

                onClick={
                    closeModal
                }

                disabled={
                    submitting
                }

            >

                Cancel

            </button>


            <button

                type="button"

                className="btn btn-primary"

                onClick={
                    handleSubmit
                }

                disabled={
                    submitting
                }

            >

                {
                    submitting

                        ? "Submitting..."

                        : "Submit Report"
                }

            </button>

        </>

    );


    // ==============================
    // RENDER
    // ==============================

    return (

        <div>

            <PageHeader

                title="Incident Management"

                description="Monitor and report GIS anomalies and road blockages. Fleet Ops module — illustrative scenario data."

                actionButton={

                    <button

                        className="btn btn-primary"

                        onClick={() =>
                            setIsModalOpen(
                                true
                            )
                        }

                    >

                        + Report Incident

                    </button>

                }

            />


            <DataSourceNote />


            {/* ==================================
                CAUSE BREAKDOWN CHART
            =================================== */}

            <div

                className="card"

                style={{
                    marginBottom:
                        "24px"
                }}

            >

                <div

                    style={{

                        display:
                            "flex",

                        justifyContent:
                            "space-between",

                        alignItems:
                            "flex-start",

                        marginBottom:
                            "4px",

                        gap:
                            16

                    }}

                >

                    <h3

                        style={{

                            fontSize:
                                "1rem",

                            fontWeight:
                                700,

                            margin:
                                0

                        }}

                    >

                        Incidents by Root Cause

                    </h3>


                    <div

                        style={{

                            fontSize:
                                "0.78rem",

                            padding:
                                "4px 10px",

                            borderRadius:
                                "10px",

                            background:
                                "rgba(239,68,68,0.12)",

                            color:
                                "#ef4444",

                            border:
                                "1px solid rgba(239,68,68,0.35)",

                            fontWeight:
                                600

                        }}

                    >

                        🔴 Landslides account for{" "}

                        {
                            landslidePercent
                        }%

                        {" "}

                        of reported incidents
                        this period

                    </div>

                </div>


                <div

                    style={{

                        fontSize:
                            "0.75rem",

                        color:
                            "var(--text-secondary)",

                        marginBottom:
                            "18px"

                    }}

                >

                    Horizontal bars sorted by frequency —
                    highest cause at top

                </div>


                {causeData.length > 0 ? (

                    <ResponsiveContainer

                        width="100%"

                        height={
                            causeData.length *
                                44 +
                            20
                        }

                    >

                        <BarChart

                            layout="vertical"

                            data={
                                causeData
                            }

                            margin={{

                                top:
                                    0,

                                right:
                                    60,

                                left:
                                    0,

                                bottom:
                                    0

                            }}

                            barSize={
                                20
                            }

                        >

                            <XAxis

                                type="number"

                                stroke="var(--border)"

                                tick={{

                                    fill:
                                        "var(--text-secondary)",

                                    fontSize:
                                        11

                                }}

                                allowDecimals={
                                    false
                                }

                            />


                            <YAxis

                                type="category"

                                dataKey="cause"

                                width={
                                    160
                                }

                                stroke="none"

                                tick={{

                                    fill:
                                        "var(--text-primary)",

                                    fontSize:
                                        12,

                                    fontWeight:
                                        500

                                }}

                            />


                            <Tooltip

                                cursor={{

                                    fill:
                                        "rgba(255,255,255,0.04)"

                                }}

                                contentStyle={{

                                    backgroundColor:
                                        "var(--surface-elevated)",

                                    border:
                                        "1px solid var(--border)",

                                    borderRadius:
                                        "6px",

                                    fontSize:
                                        "0.82rem"

                                }}

                                formatter={(
                                    value
                                ) => [

                                    `${value} incident${
                                        value !==
                                        1
                                            ? "s"
                                            : ""
                                    }`,

                                    "Count"

                                ]}

                            />


                            <Bar

                                dataKey="count"

                                radius={[
                                    0,
                                    4,
                                    4,
                                    0
                                ]}

                            >

                                {causeData.map(
                                    entry => (

                                        <Cell

                                            key={
                                                entry.cause
                                            }

                                            fill={

                                                CAUSE_COLORS[
                                                    entry.cause
                                                ] ??
                                                DEFAULT_COLOR

                                            }

                                        />

                                    )
                                )}


                                <LabelList

                                    dataKey="count"

                                    position="right"

                                    style={{

                                        fill:
                                            "var(--text-secondary)",

                                        fontSize:
                                            12,

                                        fontWeight:
                                            600

                                    }}

                                />

                            </Bar>

                        </BarChart>

                    </ResponsiveContainer>

                ) : (

                    <div

                        style={{

                            padding:
                                "30px",

                            textAlign:
                                "center",

                            color:
                                "var(--text-secondary)"

                        }}

                    >

                        No incidents reported yet.

                    </div>

                )}


                {/* ===========================
                    LEGEND
                ============================ */}

                {causeData.length > 0 && (

                    <div

                        style={{

                            display:
                                "flex",

                            gap:
                                "16px",

                            flexWrap:
                                "wrap",

                            marginTop:
                                "16px",

                            paddingTop:
                                "12px",

                            borderTop:
                                "1px solid var(--border)"

                        }}

                    >

                        {causeData.map(

                            ({
                                cause
                            }) => (

                                <div

                                    key={
                                        cause
                                    }

                                    style={{

                                        display:
                                            "flex",

                                        alignItems:
                                            "center",

                                        gap:
                                            "6px",

                                        fontSize:
                                            "0.74rem",

                                        color:
                                            "var(--text-secondary)"

                                    }}

                                >

                                    <span

                                        style={{

                                            width:
                                                10,

                                            height:
                                                10,

                                            borderRadius:
                                                2,

                                            background:

                                                CAUSE_COLORS[
                                                    cause
                                                ] ??
                                                DEFAULT_COLOR,

                                            flexShrink:
                                                0

                                        }}

                                    />


                                    {
                                        cause
                                    }

                                </div>

                            )

                        )}

                    </div>

                )}

            </div>


            {/* ==================================
                INCIDENTS TABLE
            =================================== */}

            <div className="card">

                <div className="table-container">

                    {loading ? (

                        <div

                            style={{

                                padding:
                                    "35px",

                                textAlign:
                                    "center",

                                color:
                                    "var(--text-secondary)"

                            }}

                        >

                            Loading incidents...

                        </div>

                    ) : sortedIncidents.length ===
                      0 ? (

                        <div

                            style={{

                                padding:
                                    "35px",

                                textAlign:
                                    "center",

                                color:
                                    "var(--text-secondary)"

                            }}

                        >

                            No incidents reported yet.

                        </div>

                    ) : (

                        <table>

                            <thead>

                                <tr>

                                    <th>
                                        ID
                                    </th>

                                    <th>
                                        Type
                                    </th>

                                    <th>
                                        Root Cause
                                    </th>

                                    <th>
                                        Location
                                    </th>

                                    <th>
                                        Severity
                                    </th>

                                    <th>
                                        Time Reported
                                    </th>

                                    <th>
                                        Status
                                    </th>

                                </tr>

                            </thead>


                            <tbody>

                                {sortedIncidents.map(
                                    incident => (

                                        <tr

                                            key={
                                                incident.id
                                            }

                                        >

                                            <td

                                                style={{

                                                    fontWeight:
                                                        600

                                                }}

                                            >

                                                {
                                                    incident.id
                                                }

                                            </td>


                                            <td>

                                                {
                                                    incident.type
                                                }

                                            </td>


                                            <td>

                                                <span

                                                    style={{

                                                        fontSize:
                                                            "0.75rem",

                                                        padding:
                                                            "2px 8px",

                                                        borderRadius:
                                                            8,

                                                        background:

                                                            `${
                                                                CAUSE_COLORS[
                                                                    incident.cause
                                                                ] ??
                                                                DEFAULT_COLOR
                                                            }20`,

                                                        color:

                                                            CAUSE_COLORS[
                                                                incident.cause
                                                            ] ??
                                                            DEFAULT_COLOR,

                                                        border:

                                                            `1px solid ${
                                                                CAUSE_COLORS[
                                                                    incident.cause
                                                                ] ??
                                                                DEFAULT_COLOR
                                                            }50`,

                                                        fontWeight:
                                                            600

                                                    }}

                                                >

                                                    {
                                                        incident.cause ??
                                                        incident.type
                                                    }

                                                </span>

                                            </td>


                                            <td>

                                                {
                                                    incident.location
                                                }

                                            </td>


                                            <td>

                                                <Badge>

                                                    {
                                                        incident.severity
                                                    }

                                                </Badge>

                                            </td>


                                            <td>

                                                {
                                                    incident.time
                                                }

                                            </td>


                                            <td>

                                                <Badge>

                                                    {
                                                        incident.status
                                                    }

                                                </Badge>

                                            </td>

                                        </tr>

                                    )
                                )}

                            </tbody>

                        </table>

                    )}

                </div>

            </div>


            {/* ==================================
                REPORT INCIDENT MODAL
            =================================== */}

            <Modal

                isOpen={
                    isModalOpen
                }

                onClose={
                    closeModal
                }

                title="Report New Incident"

                footer={
                    modalFooter
                }

            >

                {/* ===============================
                    INCIDENT TYPE
                ================================ */}

                <div className="form-group">

                    <label className="form-label">

                        Incident Type

                    </label>


                    <select

                        className="form-control"

                        value={
                            incidentType
                        }

                        onChange={
                            e =>
                                setIncidentType(
                                    e.target.value
                                )
                        }

                        disabled={
                            submitting
                        }

                    >

                        <option>
                            Landslide
                        </option>

                        <option>
                            Heavy Rainfall
                        </option>

                        <option>
                            Bridge / Road Damage
                        </option>

                        <option>
                            Mechanical Breakdown
                        </option>

                        <option>
                            Overspeeding
                        </option>

                        <option>
                            Other
                        </option>

                    </select>

                </div>


                {/* ===============================
                    LOCATION
                ================================ */}

                <div className="form-group">

                    <label className="form-label">

                        Location

                    </label>


                    <input

                        type="text"

                        className="form-control"

                        value={
                            locationText
                        }

                        onChange={
                            e =>
                                setLocationText(
                                    e.target.value
                                )
                        }

                        placeholder="e.g., NH-10 Sector B"

                        disabled={
                            submitting
                        }

                    />


                    {coords && (

                        <div

                            style={{

                                marginTop:
                                    6,

                                fontSize:
                                    "0.72rem",

                                color:
                                    "var(--text-secondary)",

                                display:
                                    "flex",

                                alignItems:
                                    "center",

                                gap:
                                    5

                            }}

                        >

                            <MapPin
                                size={12}
                            />

                            GPS:{" "}

                            {
                                coords.lat.toFixed(
                                    6
                                )
                            }

                            ,{" "}

                            {
                                coords.lon.toFixed(
                                    6
                                )
                            }

                        </div>

                    )}

                </div>


                {/* ===============================
                    CASUALTIES
                ================================ */}

                <div

                    style={{

                        display:
                            "grid",

                        gridTemplateColumns:
                            "1fr 1fr",

                        gap:
                            12

                    }}

                >

                    <div className="form-group">

                        <label className="form-label">

                            Deaths (if any)

                        </label>


                        <input

                            type="number"

                            min="0"

                            className="form-control"

                            value={
                                deaths
                            }

                            onChange={
                                e =>
                                    setDeaths(
                                        e.target.value
                                    )
                            }

                            placeholder="0"

                            disabled={
                                submitting
                            }

                        />

                    </div>


                    <div className="form-group">

                        <label className="form-label">

                            Injuries (if any)

                        </label>


                        <input

                            type="number"

                            min="0"

                            className="form-control"

                            value={
                                injuries
                            }

                            onChange={
                                e =>
                                    setInjuries(
                                        e.target.value
                                    )
                            }

                            placeholder="0"

                            disabled={
                                submitting
                            }

                        />

                    </div>

                </div>


                {/* ===============================
                    PHOTO
                ================================ */}

                <div className="form-group">

                    <label

                        className="form-label"

                        style={{

                            display:
                                "flex",

                            alignItems:
                                "center",

                            gap:
                                5

                        }}

                    >

                        <Camera
                            size={14}
                        />

                        Incident Photo (optional)

                    </label>


                    {photoPreview ? (

                        <div

                            style={{

                                position:
                                    "relative",

                                display:
                                    "inline-block",

                                marginBottom:
                                    6

                            }}

                        >

                            <img

                                src={
                                    photoPreview
                                }

                                alt="Preview"

                                style={{

                                    width:
                                        160,

                                    height:
                                        110,

                                    objectFit:
                                        "cover",

                                    borderRadius:
                                        8,

                                    border:
                                        "1px solid var(--line)"

                                }}

                            />


                            <button

                                type="button"

                                onClick={() =>
                                    setPhotoPreview(
                                        null
                                    )
                                }

                                disabled={
                                    submitting
                                }

                                style={{

                                    position:
                                        "absolute",

                                    top:
                                        -6,

                                    right:
                                        -6,

                                    background:
                                        "var(--danger)",

                                    color:
                                        "#fff",

                                    border:
                                        "none",

                                    borderRadius:
                                        "50%",

                                    width:
                                        20,

                                    height:
                                        20,

                                    cursor:
                                        "pointer",

                                    display:
                                        "flex",

                                    alignItems:
                                        "center",

                                    justifyContent:
                                        "center"

                                }}

                            >

                                <X
                                    size={11}
                                />

                            </button>

                        </div>

                    ) : (

                        <button

                            type="button"

                            onClick={() =>
                                fileRef.current?.click()
                            }

                            disabled={
                                submitting
                            }

                            style={{

                                display:
                                    "flex",

                                alignItems:
                                    "center",

                                gap:
                                    7,

                                padding:
                                    "8px 14px",

                                background:
                                    "var(--sky-tint)",

                                border:
                                    "1.5px dashed var(--sky-tint-2)",

                                borderRadius:
                                    8,

                                cursor:
                                    "pointer",

                                color:
                                    "var(--slate)",

                                fontSize:
                                    "0.82rem",

                                fontWeight:
                                    500

                            }}

                        >

                            <Camera
                                size={14}
                            />

                            Click to upload a photo

                        </button>

                    )}


                    <input

                        ref={
                            fileRef
                        }

                        type="file"

                        accept="image/*"

                        style={{
                            display:
                                "none"
                        }}

                        onChange={
                            handlePhoto
                        }

                    />

                </div>

            </Modal>

        </div>

    );

};